version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: attendance-ms
    container_name: attendance-ms-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - attendance-ms

  db:
    image: mysql:8.0
    container_name: attendance-ms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - attendance-ms

  nginx:
    image: nginx:alpine
    container_name: attendance-ms-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - attendance-ms

networks:
  attendance-ms:
    driver: bridge

volumes:
  dbdata: 