services:
  - type: web
    name: attendance-ms
    env: php
    buildCommand: |
      composer install --no-dev
      npm install
      npm run build
      php artisan key:generate
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: AttendanceMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: attendance-ms-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: attendance-ms-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: attendance-ms-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: attendance-ms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: attendance-ms-db
          property: password

databases:
  - name: attendance-ms-db
    databaseName: attendance_ms
    user: attendance_ms_user
    plan: free 